<?php
session_start();
$nameErr=$last_nameErr=$numberErr='';
$name=$last_name=$number="";
$id = null;
$modalWindow = '';
$message = '';
$searchParameters = [];
require_once "include/get.php";
require_once "include/functions.php";
$offsetLink = offsetLink ();
require_once "include/dataCheckFunctions.php";
require_once "include/connection.php";
require_once "include/html.php";
require_once "include/databaseFunctions.php";
head();
scripts();
frontPanel($limit);
require_once "include/databaseMain.php";
require_once "include/modalWindows.php";
displayModal($modalWindow);
selection();
pagesList(selectSQL(connection(), $offset, $limit, $searchParameters), $limit, $offset, $offsetLink, $searchParameters);
table(selectSQL(connection(), $offset, $limit, $searchParameters),$offset, $limit);
pagesList(selectSQL(connection(), $offset, $limit, $searchParameters), $limit, $offset, $offsetLink, $searchParameters);
foot();